<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Messenger.Logging\Messenger.Logging.csproj"/>
        <ProjectReference Include="..\Messenger.Shared\Messenger.Shared.csproj"/>
    </ItemGroup>

</Project>
